### ISSUE TITLE
Problem with connection 

### ISSUE THREAD

**Issue by pawelm7** [hrbrmstr/darksky#17]
Hi,

could you check your R code. I have answer with error:

> tmp <- get_current_forecast(37.8267, -122.423)
Błąd w poleceniu 'curl::curl_fetch_memory(url, handle = handle)':
  Failed to connect to api.darksky.net port 443: Timed out

Thanks a lot:)
Pawel

**Comment by hrbrmstr** [comment]
Well, I would but I have no idea of your setup (and that error doesn't usually indicate an issue with the package code and you'll note you're the only one with this issue — so far, at least).

Output of `sessionInfo()` or the `devtools` equiv wld be appreciated.

**Comment by hrbrmstr** [comment]
And, via the CRAN version (just ran):

```r
library(darksky)

tmp <- get_current_forecast(37.8267, -122.423)
str(tmp, 1)
## List of 4
##  $ hourly   :'data.frame':  49 obs. of  18 variables:
##  $ minutely :'data.frame':  61 obs. of  5 variables:
##  $ daily    :'data.frame':  8 obs. of  39 variables:
##  $ currently:'data.frame':  1 obs. of  19 variables:
##  - attr(*, "class")= chr [1:3] "darksky" "current" "list"
```

**Comment by pawelm7** [comment]
Hello,

I am sorry that I did not provide detailed information before but I did not know what to provide. I consulted this problem with my IT specialist and unfortunately, in our network all traffic is directed by a proxy server. These are the security issues. we checked how the script downloads data and it turns out that the firewall blocks it because it wants to go directly through port 443 and not through a proxy server. Please, let me know if there is a possibility to configure the darksky script?

Best wishes

Pawel

**Comment by pawelm7** [comment]
Hi, 
some additional information:
> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=Polish_Poland.1250  LC_CTYPE=Polish_Poland.1250   
[3] LC_MONETARY=Polish_Poland.1250 LC_NUMERIC=C                  
[5] LC_TIME=Polish_Poland.1250    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.2

Can you give me some tips?
Pawel

**Comment by pawelm7** [comment]
@hrbrmstr

**Comment by hrbrmstr** [comment]
FWIW patience is a virtue. This is not a commercial program nor is the package part of what I use daily for work. Please refrain from assuming your needs require immediate attention when posting issues to open source projects.

**Comment by hrbrmstr** [comment]
having said that (i really shouldn't respond right now as it might encourage such behavior) please also take time to read the package manual pages.

https://github.com/hrbrmstr/darksky/blob/master/R/get-current-forecast.r#L37-L38 would have been an indicator of how to accomplish what you need. You can review the `httr` package documentation to see what needs to be filled in there (it'll be good practice in reading docs).

**Comment by pawelm7** [comment]
Thank you very much for the tips and at the same time I apologize for the inconvenience but I did not know if the news reached you. I rarely use ready-made solutions on the web and usually I am looking for something myself, but this case is special and I had to use your goodness :) I hope I did not abuse it.

Best wishes

**Comment by pawelm7** [comment]
Hi,

thanks for help. It works:
install.packages("httr")
library(httr)

set_config(use_proxy(url="your.proxyserver.com", port=8080, username="proxy_username", password="proxy_password")) 

regards
