### ISSUE TITLE
Problem with new version (0.7.0) of dplyr

### ISSUE THREAD

**Issue by dponton** [hrbrmstr/darksky#4]
Thanks for your very useful package!

With v0.7.0 of dplyr, I now get the following message when using "get_forecast_for"

`mutate_each()` is deprecated.
Use `mutate_all()`, `mutate_at()` or `mutate_if()` instead.
To map `funs` over a selection of variables, use `mutate_at()`
`mutate_each()` is deprecated.
Use `mutate_all()`, `mutate_at()` or `mutate_if()` instead.
To map `funs` over a selection of variables, use `mutate_at()`

**Comment by DamonWoods** [comment]
I am also having this issue. The warnings of "mutate_each() is deprecated" prevent me from automating my script. Is there any work-around?
