### ISSUE TITLE
CRAN release?

### ISSUE THREAD

**Issue by krlmlr** [hrbrmstr/darksky#8]
I'm wondering if you were planning a CRAN release anytime soon, to avoid warnings about dplyr incompatibilities. I've been using the GitHub version without any problems so far. Thanks!

**Comment by hrbrmstr** [comment]
Absentmindedness more than anything else. I shall try to get it to them today. #ty for the reminder.

**Comment by hrbrmstr** [comment]
on its way!

**Comment by hrbrmstr** [comment]
and making its way to mirrors.

**Comment by krlmlr** [comment]
Awesome, thanks!
