### ISSUE TITLE
What is convert_time function doing? 

### ISSUE THREAD

**Issue by gmarwaha** [hrbrmstr/darksky#9]
New to GitHub - not sure if there is another (better) way to ask a question here:
I don't understand what the `convert_time` is doing (lines 90, 107 of get-current-forecast.r). It is not being imported and is not defined within the code. I checked the `NAMESPACE` and didn't find anything there either - `ggplot2` and `gtable` are being imported but they do not seem to have this function other packages have specific functions that are imported.

**Comment by hrbrmstr** [comment]
https://github.com/hrbrmstr/darksky/search?utf8=%E2%9C%93&q=convert_time&type=

**Comment by gmarwaha** [comment]
Got it, thanks!
